[package]
name = "replicator"
version = "0.1.0"
edition = "2021"

[dependencies]
bytebuffer = "2.3.0"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
memory-stats = "1.2.0"
serde_json = {version="1.0.132"}
