@startuml OpCodes

rectangle "Opcode 5.2" as n1 {
    node "ktudh 32 bytes" as n11 #palegreen
    node "kteop 36 bytes" as n12
    node "pdb 4 bytes" as n13
    circle end as n24

    n11 --> n12
    n11 --> n13 
    n12 --> n13

    n11 --> n24
    n12 --> n24
    n13 --> n24
}

rectangle "Opcode 5.4" as n2 {
    node "ktucm 20 bytes" as n21 #palegreen
    node "ktucf 16 bytes" as n22
    circle end as n23

    n21 --> n22
    
    n21 --> n23
    n22 --> n23
}

rectangle "Opcode 5.20" as n3 {
    node "attr1 4/8 bytes" as n31 #palegreen
    node "attr2 ? bytes" as n32 #palegreen
    node "attr3 6 bytes" as n33 #palegreen
    node "attr4 4 bytes" as n34 #palegreen
    node "attr5 4 bytes" as n35 #palegreen
    node "attr6 ? bytes" as n36 #palegreen
    node "attr7 ? bytes" as n37 #palegreen
    node "attr8 ? bytes" as n38 #palegreen
    circle end as n39

    n31 -> n32
    n32 --> n33
    n33 -> n34
    n34 --> n35
    n35 -> n36
    n36 --> n37
    n37 -> n38
    n38 -> n39
}


@enduml
