

use super::types::{TypeConId, TypeScn, TypeTimestamp, TypeXid};

#[derive(Debug, Default)]
pub struct LogminerRow {
    scn : TypeScn,
    start_scn : TypeScn,
    commit_scn : TypeScn,
    timestamp : TypeTimestamp,
    start_timestamp : TypeTimestamp,
    commit_timestamp : TypeTimestamp,
    xid : TypeXid,
    pxid : TypeXid,
    tx_name : String,
    operation_code : u8,
    rollback : bool,
    seg_owner : String,
    seg_name : String,
    table_name : String,
    seg_type : u8,
    table_space : String,
    username : String,
    os_username : String,
    machine_name : String,
    audit_session_id : u32,
    session : u32,
    serial : u32,
    session_info : String,
    thread : u64,
    sequence : u64,
    rbasqn : u64,
    rbablk : u64,
    rbabyte : u64,
    ubafil : u64,
    ubablk : u64,
    ubarec : u64,
    ubasqn : u64,
    abs_file : u64,
    rel_file : u64,
    data_blk : u64,
    data_obj : u64,
    data_objv : u64,
    data_objd : u64,
    con_id : TypeConId,
}
